version: 0.2
phases: 
  install: 
    runtime-versions:
      python: 3.8
    commands:
      - yum update -y && yum install -y unzip git
      - curl -Lo terraform.zip https://releases.hashicorp.com/terraform/1.8.4/terraform_1.8.4_linux_amd64.zip
      - unzip terraform.zip -d /usr/local/bin/
      - rm terraform.zip
  build: 
    commands:
      - git clone https://github.com/zhemein/scbzorro
      - echo '$TF_VAR_dbusername'
      - echo '$TF_VAR_dbpassword'
      - #cd scbzorro && terraform init
      - #terraform plan
      - #terraform apply -auto-approve